### ISSUE TITLE
Combobox Support

### ISSUE THREAD

**Issue by DaanVervacke** [sveltecult/franken-ui#8]
Are there any plans to include a component similar to shadcn's combobox?
[Reference](https://ui.shadcn.com/docs/components/combobox)

Thanks!

**Comment by sveltecult** [comment]
Hello,

The direction of this library has changed to be framework-agnostic and HTML-first. For now, I don't see myself adding combobox. But, it's very easy to do because all elements you need to build one is already there, see this as an example: https://mas.to/@sveltecult/112402965900231702 and for the datepicker: https://github.com/sveltecult/franken-ui-site/issues/2

If there's a possibility then it would be a separate project and is Alpine+HTMX-specific.
